name = "sequoia-docs"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[assets]
directory = "./docs/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
html_handling = "auto-trailing-slash"
run_worker_first = ["/api/*", "/oauth/*"]
